vpx set dofile abort exit
vpx set screen display -noprogress
tclmode

# Generated by Genus(TM) Synthesis Solution 17.22-s017_1, revision 1.272a
# Generated on: Mon Feb 27 17:25:14 IST 2023 (Mon Feb 27 11:55:14 GMT 2023)

set lec_version [regsub {(-).} $env(LEC_VERSION) ""]

tcl_set_command_name_echo on

set_log_file logs_Feb27-17:22:39/intermediate2final.lec.log -replace

usage -auto -elapse

set_verification_information fv_map_booth_radix4_multiplier_mv_db

read_implementation_information fv/booth_radix4_multiplier -golden fv_map -revised booth_radix4_multiplier_mv

set_parallel_option -threads 4 -license "xl lp gxl lpgxl eco ecogxl" -norelease_license

set env(RC_VERSION)     "17.22-s017_1"
set env(CDN_SYNTH_ROOT) "/tools/cadence/GENUS172/tools.lnx86"
set CDN_SYNTH_ROOT      "/tools/cadence/GENUS172/tools.lnx86"
set env(CW_DIR) "/tools/cadence/GENUS172/tools.lnx86/lib/chipware"
set CW_DIR      "/tools/cadence/GENUS172/tools.lnx86/lib/chipware"

# default is to error out when module definitions are missing
set_undefined_cell black_box -noascend -both

add_search_path ../lib -library -both
read_library -liberty -both   /home/sgeuser114/Desktop/venkat/singleCycleProcessor/PPGen/work/../lib/fast.lib /home/sgeuser114/Desktop/venkat/singleCycleProcessor/PPGen/work/../lib/slow.lib /home/sgeuser114/Desktop/venkat/singleCycleProcessor/PPGen/work/../lib/fast.lib /home/sgeuser114/Desktop/venkat/singleCycleProcessor/PPGen/work/../lib/slow.lib

read_design -verilog95   -golden -lastmod -noelab fv/booth_radix4_multiplier/fv_map.v.gz
elaborate_design -golden -root {booth_radix4_multiplier}

read_design -verilog95   -revised -lastmod -noelab outputs_Feb27-17:22:39/booth_radix4_multiplier_m.v
elaborate_design -revised -root {booth_radix4_multiplier}

report_design_data
report_black_box

set_flatten_model -seq_constant
set_flatten_model -seq_constant_x_to 0
set_flatten_model -nodff_to_dlat_zero
set_flatten_model -nodff_to_dlat_feedback
set_flatten_model -hier_seq_merge

set_analyze_option -auto

set_system_mode lec
report_unmapped_points -summary
report_unmapped_points -extra -unreachable -notmapped
add_compared_points -all
compare

report_compare_data -class nonequivalent -class abort -class notcompared
report_verification -verbose
report_statistics

write_verification_information
report_verification_information

tclmode
puts "No of compare points = [get_compare_points -count]"
puts "No of diff points    = [get_compare_points -NONequivalent -count]"
puts "No of abort points   = [get_compare_points -abort -count]"
puts "No of unknown points = [get_compare_points -unknown -count]"
if {[get_compare_points -count] == 0} {
    puts "---------------------------------"
    puts "ERROR: No compare points detected"
    puts "---------------------------------"
}
if {[get_compare_points -NONequivalent -count] > 0} {
    puts "------------------------------------"
    puts "ERROR: Different Key Points detected"
    puts "------------------------------------"
}
if {[get_compare_points -abort -count] > 0} {
    puts "-----------------------------"
    puts "ERROR: Abort Points detected "
    puts "-----------------------------"
}
if {[get_compare_points -unknown -count] > 0} {
    puts "----------------------------------"
    puts "ERROR: Unknown Key Points detected"
    puts "----------------------------------"
}
vpxmode
exit -f
